/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.calcolatrice;

/**
 *
 * @author tss
 */
public class Calcolatrice extends javax.swing.JFrame {

    /**
     * Creates new form Calcolatrice
     */
    double num, ans;
    int calculation;

    public void aritmetica() {
        switch (calculation) {
            case 1:
                ans = num + Double.parseDouble(tFattori.getText());
                tFattori.setText(Double.toString(ans));
                break;
            case 2:
                ans = num - Double.parseDouble(tFattori.getText());
                tFattori.setText(Double.toString(ans));
                break;
            case 3:
                ans = num / Double.parseDouble(tFattori.getText());
                tFattori.setText(Double.toString(ans));
                break;
            case 4:
                ans = num * Double.parseDouble(tFattori.getText());
                tFattori.setText(Double.toString(ans));
                break;

        }

    }

    public Calcolatrice() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tFattori = new javax.swing.JTextField();
        bZero = new javax.swing.JButton();
        bDoppioZero = new javax.swing.JButton();
        bVirgola = new javax.swing.JButton();
        bUno = new javax.swing.JButton();
        bUguale = new javax.swing.JButton();
        bDue = new javax.swing.JButton();
        bTre = new javax.swing.JButton();
        bQuattro = new javax.swing.JButton();
        bCinque = new javax.swing.JButton();
        bMoltiplicazione = new javax.swing.JButton();
        bSei = new javax.swing.JButton();
        bSette = new javax.swing.JButton();
        bOtto = new javax.swing.JButton();
        bNove = new javax.swing.JButton();
        bSottrazione = new javax.swing.JButton();
        bCancella = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        bPercentuale = new javax.swing.JButton();
        bDivisione = new javax.swing.JButton();
        bAddizione = new javax.swing.JButton();
        lVisualizzaOperazioni = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tFattori.setEditable(false);
        tFattori.setBackground(new java.awt.Color(1, 1, 1));
        tFattori.setForeground(new java.awt.Color(254, 254, 254));
        tFattori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFattoriActionPerformed(evt);
            }
        });

        bZero.setText("0");
        bZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bZeroActionPerformed(evt);
            }
        });

        bDoppioZero.setBackground(new java.awt.Color(46, 52, 54));
        bDoppioZero.setText("00");
        bDoppioZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDoppioZeroActionPerformed(evt);
            }
        });

        bVirgola.setBackground(new java.awt.Color(46, 52, 54));
        bVirgola.setText(".");
        bVirgola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVirgolaActionPerformed(evt);
            }
        });

        bUno.setBackground(new java.awt.Color(46, 52, 54));
        bUno.setText("1");
        bUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUnoActionPerformed(evt);
            }
        });

        bUguale.setBackground(new java.awt.Color(255, 129, 0));
        bUguale.setText("=");
        bUguale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUgualeActionPerformed(evt);
            }
        });

        bDue.setBackground(new java.awt.Color(46, 52, 54));
        bDue.setText("2");
        bDue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDueActionPerformed(evt);
            }
        });

        bTre.setBackground(new java.awt.Color(46, 52, 54));
        bTre.setText("3");
        bTre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTreActionPerformed(evt);
            }
        });

        bQuattro.setBackground(new java.awt.Color(46, 52, 54));
        bQuattro.setText("4");
        bQuattro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bQuattroActionPerformed(evt);
            }
        });

        bCinque.setBackground(new java.awt.Color(46, 52, 54));
        bCinque.setText("5");
        bCinque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCinqueActionPerformed(evt);
            }
        });

        bMoltiplicazione.setBackground(new java.awt.Color(255, 129, 0));
        bMoltiplicazione.setText("*");
        bMoltiplicazione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMoltiplicazioneActionPerformed(evt);
            }
        });

        bSei.setBackground(new java.awt.Color(46, 52, 54));
        bSei.setText("6");
        bSei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSeiActionPerformed(evt);
            }
        });

        bSette.setBackground(new java.awt.Color(46, 52, 54));
        bSette.setText("7");
        bSette.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSetteActionPerformed(evt);
            }
        });

        bOtto.setBackground(new java.awt.Color(46, 52, 54));
        bOtto.setText("8");
        bOtto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOttoActionPerformed(evt);
            }
        });

        bNove.setBackground(new java.awt.Color(46, 52, 54));
        bNove.setText("9");
        bNove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNoveActionPerformed(evt);
            }
        });

        bSottrazione.setBackground(new java.awt.Color(255, 129, 0));
        bSottrazione.setText("-");
        bSottrazione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSottrazioneActionPerformed(evt);
            }
        });

        bCancella.setBackground(new java.awt.Color(255, 129, 0));
        bCancella.setText("C");
        bCancella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancellaActionPerformed(evt);
            }
        });

        bReset.setBackground(new java.awt.Color(255, 129, 0));
        bReset.setText("CE");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        bPercentuale.setBackground(new java.awt.Color(255, 129, 0));
        bPercentuale.setText("%");

        bDivisione.setBackground(new java.awt.Color(255, 129, 0));
        bDivisione.setText("/");
        bDivisione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDivisioneActionPerformed(evt);
            }
        });

        bAddizione.setBackground(new java.awt.Color(255, 129, 0));
        bAddizione.setText("+");
        bAddizione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddizioneActionPerformed(evt);
            }
        });

        lVisualizzaOperazioni.setBackground(new java.awt.Color(1, 1, 1));
        lVisualizzaOperazioni.setForeground(new java.awt.Color(255, 129, 0));
        lVisualizzaOperazioni.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lVisualizzaOperazioni.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tFattori)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bCancella, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bSei, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bZero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bDue, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bTre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bDoppioZero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bSette, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bVirgola, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bQuattro, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bOtto, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bPercentuale, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bDivisione, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bNove, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(bCinque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bUno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bMoltiplicazione, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bUguale, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(bAddizione, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bSottrazione, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lVisualizzaOperazioni, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lVisualizzaOperazioni, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tFattori, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancella, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDivisione, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPercentuale, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAddizione, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSei, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSette, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bOtto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bNove, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSottrazione, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bDue, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bTre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bQuattro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCinque, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bMoltiplicazione, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bZero, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDoppioZero, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bVirgola, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bUno, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bUguale, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bDoppioZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDoppioZeroActionPerformed
        // TODO add your handling code here:
        tFattori.setText(tFattori.getText() + "00");

    }//GEN-LAST:event_bDoppioZeroActionPerformed

    private void bZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bZeroActionPerformed
        // TODO add your handling code here:
        tFattori.setText(tFattori.getText() + "0");
    }//GEN-LAST:event_bZeroActionPerformed

    private void bVirgolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVirgolaActionPerformed
        // TODO add your handling code here:
        tFattori.setText(tFattori.getText() + ".");
    }//GEN-LAST:event_bVirgolaActionPerformed

    private void bUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUnoActionPerformed
        // TODO add your handling code here:
        tFattori.setText(tFattori.getText() + "1");
    }//GEN-LAST:event_bUnoActionPerformed

    private void bDueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDueActionPerformed
        // TODO add your handling code here:
        tFattori.setText(tFattori.getText() + "2");
    }//GEN-LAST:event_bDueActionPerformed

    private void bTreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTreActionPerformed
        // TODO add your handling code here:
        tFattori.setText(tFattori.getText() + "3");
    }//GEN-LAST:event_bTreActionPerformed

    private void bQuattroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bQuattroActionPerformed
        // TODO add your handling code here:
        tFattori.setText(tFattori.getText() + "4");
    }//GEN-LAST:event_bQuattroActionPerformed

    private void bCinqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCinqueActionPerformed
        // TODO add your handling code here:
        tFattori.setText(tFattori.getText() + "5");
    }//GEN-LAST:event_bCinqueActionPerformed

    private void bSeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSeiActionPerformed
        // TODO add your handling code here:
        tFattori.setText(tFattori.getText() + "6");
    }//GEN-LAST:event_bSeiActionPerformed

    private void bSetteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSetteActionPerformed
        // TODO add your handling code here:
        tFattori.setText(tFattori.getText() + "7");
    }//GEN-LAST:event_bSetteActionPerformed

    private void bOttoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOttoActionPerformed
        // TODO add your handling code here:
        tFattori.setText(tFattori.getText() + "8");
    }//GEN-LAST:event_bOttoActionPerformed

    private void bNoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNoveActionPerformed
        // TODO add your handling code here:
        tFattori.setText(tFattori.getText() + "9");
    }//GEN-LAST:event_bNoveActionPerformed

    private void tFattoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFattoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFattoriActionPerformed

    private void bMoltiplicazioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMoltiplicazioneActionPerformed
        num = Double.parseDouble(tFattori.getText());
        calculation = 4;
        tFattori.setText("");
        lVisualizzaOperazioni.setText(num + " * ");
    
    }//GEN-LAST:event_bMoltiplicazioneActionPerformed

    private void bSottrazioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSottrazioneActionPerformed
        // TODO add your handling code here:
        num = Double.parseDouble(tFattori.getText());
        calculation = 2;
        tFattori.setText("");
        lVisualizzaOperazioni.setText(num + " - ");
    
    }//GEN-LAST:event_bSottrazioneActionPerformed

    private void bAddizioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddizioneActionPerformed
        // TODO add your handling code here:
        num = Double.parseDouble(tFattori.getText());
        calculation = 1;
        tFattori.setText("");
        lVisualizzaOperazioni.setText(num + " + ");
    }//GEN-LAST:event_bAddizioneActionPerformed

    private void bDivisioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDivisioneActionPerformed
        // TODO add your handling code here:
        num = Double.parseDouble(tFattori.getText());
        calculation = 3;
        tFattori.setText("");
        lVisualizzaOperazioni.setText(num + " / ");
    
    }//GEN-LAST:event_bDivisioneActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        // TODO add your handling code here:
        int length = tFattori.getText().length();
        int number = tFattori.getText().length() - 1;
        String store;

        if (length > 0) {
            StringBuilder back = new StringBuilder(tFattori.getText());
            back.deleteCharAt(number);
            store = back.toString();
            tFattori.setText(store);
        }
    }//GEN-LAST:event_bResetActionPerformed

    private void bCancellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancellaActionPerformed
        // TODO add your handling code here:
        tFattori.setText("");
    }//GEN-LAST:event_bCancellaActionPerformed

    private void bUgualeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUgualeActionPerformed
        // TODO add your handling code here:
        aritmetica();
        lVisualizzaOperazioni.setText("");
    }//GEN-LAST:event_bUgualeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calcolatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calcolatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calcolatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calcolatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calcolatrice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddizione;
    private javax.swing.JButton bCancella;
    private javax.swing.JButton bCinque;
    private javax.swing.JButton bDivisione;
    private javax.swing.JButton bDoppioZero;
    private javax.swing.JButton bDue;
    private javax.swing.JButton bMoltiplicazione;
    private javax.swing.JButton bNove;
    private javax.swing.JButton bOtto;
    private javax.swing.JButton bPercentuale;
    private javax.swing.JButton bQuattro;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bSei;
    private javax.swing.JButton bSette;
    private javax.swing.JButton bSottrazione;
    private javax.swing.JButton bTre;
    private javax.swing.JButton bUguale;
    private javax.swing.JButton bUno;
    private javax.swing.JButton bVirgola;
    private javax.swing.JButton bZero;
    private javax.swing.JLabel lVisualizzaOperazioni;
    private javax.swing.JTextField tFattori;
    // End of variables declaration//GEN-END:variables
}
